name: YY AI
title: YY AI | AI with Yvette Tsai
description: About AI, ML, LLMs and more by Yvette Tsai.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
  - prompt engineering
  - vector databases
  - input processing
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: tsaimc2@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xvgwyrvw